kind: Deployment
apiVersion: apps/v1
metadata:
  name: tfh-task
  labels:
    app: tfh-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfh-task
  template:
    metadata:
      labels:
        app: tfh-task
    spec:
      containers:
        - name: tfh-task
          image: "sockmal/tfh-task:0.4.0"
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
                memory: "256Mi"
                cpu: "500m"
            limits:
                memory: "512Mi"
                cpu: "900m"

---

kind: Service
apiVersion: v1
metadata:
  name: tfh-task-service
spec:
  selector:
    app: tfh-task
  ports:
    - port: 8080 # Default port for image

---

apiVersion: v1
kind: Route
metadata:
  name: tfh-task-service
spec:
  #path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tfh-task-service