kind: Deployment
apiVersion: apps/v1
metadata:
  name: tfh-ms
  labels:
    app: tfh-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfh-ms
  template:
    metadata:
      labels:
        app: tfh-ms
    spec:
      containers:
        - name: tfh-ms
          image: "sockmal/tfh-ms:0.8.0"
          ports:
          - containerPort: 8080
          env:
          - name: USER_DB
            valueFrom:
              secretKeyRef:
                name: tfh-ms-secret
                key: username
          - name: PWD_DB
            valueFrom:
              secretKeyRef:
                name: tfh-ms-secret
                key: password
          - name: URL_DB
            valueFrom:
              configMapKeyRef:
                name: tfh-ms-config
                key: uriBase
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
                memory: "256Mi"
                cpu: "500m"
            limits:
                memory: "512Mi"
                cpu: "900m"

---

kind: Service
apiVersion: v1
metadata:
  name: tfh-ms-service
spec:
  selector:
    app: tfh-ms
  ports:
    - port: 8080 # Default port for image

---

apiVersion: v1
kind: Route
metadata:
  name: tfh-ms-service
spec:
  #path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tfh-ms-service